layout_spectrum: 0.8303389
typography_spectrum: 0.09436427
color:
  saturation: 0.6017232
  lightness: 0.6824126
  brandStrength: 0.2734545
  rhythmicContrast: 0.2724752
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Max
